Imports System.IO
Imports System.Text
Imports System.Diagnostics

Public Module ReportHelper

    Private Function GetLogoBase64() As String
        Try
            ' 1. Check local output img folder
            Dim localImgPath As String = Path.Combine(Application.StartupPath, "img", "barangay_logo.png")
            If File.Exists(localImgPath) Then
                Dim bytes As Byte() = File.ReadAllBytes(localImgPath)
                Return "data:image/png;base64," & Convert.ToBase64String(bytes)
            End If

            ' 2. Check base directory
            Dim baseImgPath As String = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "img", "barangay_logo.png")
            If File.Exists(baseImgPath) Then
                Dim bytes As Byte() = File.ReadAllBytes(baseImgPath)
                Return "data:image/png;base64," & Convert.ToBase64String(bytes)
            End If

            ' 3. Fallback to AdminDashboardForm resource manager
            Dim resources As New System.ComponentModel.ComponentResourceManager(GetType(AdminDashboardForm))
            Dim img As Image = TryCast(resources.GetObject("PictureBox1.Image"), Image)
            If img IsNot Nothing Then
                Using ms As New MemoryStream()
                    img.Save(ms, System.Drawing.Imaging.ImageFormat.Png)
                    Return "data:image/png;base64," & Convert.ToBase64String(ms.ToArray())
                End Using
            End If
        Catch ex As Exception
            ' Silently continue without logo if unavailable
        End Try
        Return ""
    End Function

    Public Sub PrintDocumentArchiveReport()
        Try
            Dim dt As DataTable = DocumentRepository.GetAll()
            Dim logoDataUrl As String = GetLogoBase64()

            Dim totalDocs As Integer = dt.Rows.Count
            Dim approvedCount As Integer = 0
            Dim pendingCount As Integer = 0

            For Each row As DataRow In dt.Rows
                Dim st As String = If(row("ApprovalStatus") IsNot Nothing, row("ApprovalStatus").ToString(), "")
                If st = "Approved" Then
                    approvedCount += 1
                ElseIf st = "For Review" Then
                    pendingCount += 1
                End If
            Next

            Dim sb As New StringBuilder()
            sb.AppendLine("<!DOCTYPE html>")
            sb.AppendLine("<html lang=""en"">")
            sb.AppendLine("<head>")
            sb.AppendLine("  <meta charset=""UTF-8"">")
            sb.AppendLine("  <title>Document Archive Master Report - Barangay Sto. Domingo</title>")
            sb.AppendLine("  <style>")
            sb.AppendLine("    * { box-sizing: border-box; }")
            sb.AppendLine("    body {")
            sb.AppendLine("      font-family: 'Segoe UI', Arial, sans-serif;")
            sb.AppendLine("      margin: 0;")
            sb.AppendLine("      padding: 24px;")
            sb.AppendLine("      background-color: #f7f5ed;")
            sb.AppendLine("      color: #2b3a2c;")
            sb.AppendLine("      -webkit-print-color-adjust: exact;")
            sb.AppendLine("      print-color-adjust: exact;")
            sb.AppendLine("    }")
            sb.AppendLine("    .report-card {")
            sb.AppendLine("      max-width: 1200px;")
            sb.AppendLine("      margin: 0 auto;")
            sb.AppendLine("      background: #ffffff;")
            sb.AppendLine("      border: 1px solid #d4dec9;")
            sb.AppendLine("      border-radius: 8px;")
            sb.AppendLine("      padding: 32px;")
            sb.AppendLine("      box-shadow: 0 4px 14px rgba(0,0,0,0.06);")
            sb.AppendLine("    }")
            sb.AppendLine("    /* Header styling */")
            sb.AppendLine("    .report-header {")
            sb.AppendLine("      display: flex;")
            sb.AppendLine("      align-items: center;")
            sb.AppendLine("      justify-content: space-between;")
            sb.AppendLine("      border-bottom: 3px double #346739;")
            sb.AppendLine("      padding-bottom: 18px;")
            sb.AppendLine("      margin-bottom: 20px;")
            sb.AppendLine("    }")
            sb.AppendLine("    .header-logo {")
            sb.AppendLine("      width: 85px;")
            sb.AppendLine("      height: 85px;")
            sb.AppendLine("      object-fit: contain;")
            sb.AppendLine("    }")
            sb.AppendLine("    .header-text {")
            sb.AppendLine("      text-align: center;")
            sb.AppendLine("      flex: 1;")
            sb.AppendLine("      padding: 0 15px;")
            sb.AppendLine("    }")
            sb.AppendLine("    .header-text .gov-title {")
            sb.AppendLine("      font-size: 11pt;")
            sb.AppendLine("      text-transform: uppercase;")
            sb.AppendLine("      letter-spacing: 0.5px;")
            sb.AppendLine("      color: #555;")
            sb.AppendLine("      margin: 0 0 2px 0;")
            sb.AppendLine("    }")
            sb.AppendLine("    .header-text .brgy-title {")
            sb.AppendLine("      font-size: 16pt;")
            sb.AppendLine("      font-weight: bold;")
            sb.AppendLine("      color: #346739;")
            sb.AppendLine("      margin: 0 0 3px 0;")
            sb.AppendLine("    }")
            sb.AppendLine("    .header-text .system-title {")
            sb.AppendLine("      font-size: 12pt;")
            sb.AppendLine("      font-weight: 600;")
            sb.AppendLine("      color: #79ae6f;")
            sb.AppendLine("      margin: 0;")
            sb.AppendLine("    }")
            sb.AppendLine("    .report-title-bar {")
            sb.AppendLine("      background-color: #346739;")
            sb.AppendLine("      color: #f2edc2;")
            sb.AppendLine("      text-align: center;")
            sb.AppendLine("      padding: 8px 12px;")
            sb.AppendLine("      font-size: 13pt;")
            sb.AppendLine("      font-weight: bold;")
            sb.AppendLine("      letter-spacing: 1px;")
            sb.AppendLine("      border-radius: 4px;")
            sb.AppendLine("      margin-bottom: 18px;")
            sb.AppendLine("    }")
            sb.AppendLine("    /* Stats summary */")
            sb.AppendLine("    .summary-pills {")
            sb.AppendLine("      display: flex;")
            sb.AppendLine("      gap: 12px;")
            sb.AppendLine("      flex-wrap: wrap;")
            sb.AppendLine("      margin-bottom: 20px;")
            sb.AppendLine("    }")
            sb.AppendLine("    .pill {")
            sb.AppendLine("      flex: 1;")
            sb.AppendLine("      min-width: 140px;")
            sb.AppendLine("      background: #fbfbf6;")
            sb.AppendLine("      border: 1px solid #d5dec8;")
            sb.AppendLine("      border-radius: 6px;")
            sb.AppendLine("      padding: 10px 14px;")
            sb.AppendLine("      text-align: center;")
            sb.AppendLine("    }")
            sb.AppendLine("    .pill .pill-num {")
            sb.AppendLine("      font-size: 18pt;")
            sb.AppendLine("      font-weight: bold;")
            sb.AppendLine("      color: #346739;")
            sb.AppendLine("    }")
            sb.AppendLine("    .pill .pill-label {")
            sb.AppendLine("      font-size: 8.5pt;")
            sb.AppendLine("      text-transform: uppercase;")
            sb.AppendLine("      color: #666;")
            sb.AppendLine("      margin-top: 2px;")
            sb.AppendLine("    }")
            sb.AppendLine("    /* Action Bar (hidden on print) */")
            sb.AppendLine("    .action-bar {")
            sb.AppendLine("      display: flex;")
            sb.AppendLine("      align-items: center;")
            sb.AppendLine("      justify-content: space-between;")
            sb.AppendLine("      gap: 12px;")
            sb.AppendLine("      background: #eef3e8;")
            sb.AppendLine("      border: 1px solid #c9d8be;")
            sb.AppendLine("      border-radius: 6px;")
            sb.AppendLine("      padding: 12px 16px;")
            sb.AppendLine("      margin-bottom: 20px;")
            sb.AppendLine("    }")
            sb.AppendLine("    .btn-print {")
            sb.AppendLine("      background-color: #346739;")
            sb.AppendLine("      color: #ffffff;")
            sb.AppendLine("      border: none;")
            sb.AppendLine("      border-radius: 4px;")
            sb.AppendLine("      padding: 9px 20px;")
            sb.AppendLine("      font-size: 10pt;")
            sb.AppendLine("      font-weight: bold;")
            sb.AppendLine("      cursor: pointer;")
            sb.AppendLine("      display: inline-flex;")
            sb.AppendLine("      align-items: center;")
            sb.AppendLine("      gap: 8px;")
            sb.AppendLine("      transition: background 0.2s;")
            sb.AppendLine("    }")
            sb.AppendLine("    .btn-print:hover { background-color: #264c2a; }")
            sb.AppendLine("    .search-box {")
            sb.AppendLine("      padding: 8px 12px;")
            sb.AppendLine("      font-size: 9.5pt;")
            sb.AppendLine("      border: 1px solid #b8c9ad;")
            sb.AppendLine("      border-radius: 4px;")
            sb.AppendLine("      width: 280px;")
            sb.AppendLine("    }")
            sb.AppendLine("    .filter-btn {")
            sb.AppendLine("      padding: 6px 12px;")
            sb.AppendLine("      font-size: 8.5pt;")
            sb.AppendLine("      border: 1px solid #79ae6f;")
            sb.AppendLine("      border-radius: 3px;")
            sb.AppendLine("      background: #ffffff;")
            sb.AppendLine("      cursor: pointer;")
            sb.AppendLine("      font-weight: 600;")
            sb.AppendLine("      color: #346739;")
            sb.AppendLine("    }")
            sb.AppendLine("    .filter-btn.active {")
            sb.AppendLine("      background: #346739;")
            sb.AppendLine("      color: #ffffff;")
            sb.AppendLine("    }")
            sb.AppendLine("    /* Table styling */")
            sb.AppendLine("    table.archive-table {")
            sb.AppendLine("      width: 100%;")
            sb.AppendLine("      border-collapse: collapse;")
            sb.AppendLine("      margin-bottom: 24px;")
            sb.AppendLine("      font-size: 9.5pt;")
            sb.AppendLine("    }")
            sb.AppendLine("    table.archive-table th {")
            sb.AppendLine("      background-color: #346739;")
            sb.AppendLine("      color: #f2edc2;")
            sb.AppendLine("      text-align: left;")
            sb.AppendLine("      padding: 10px 10px;")
            sb.AppendLine("      font-weight: 600;")
            sb.AppendLine("      font-size: 9pt;")
            sb.AppendLine("      border: 1px solid #28502c;")
            sb.AppendLine("      cursor: pointer;")
            sb.AppendLine("      user-select: none;")
            sb.AppendLine("      white-space: nowrap;")
            sb.AppendLine("    }")
            sb.AppendLine("    table.archive-table th:hover {")
            sb.AppendLine("      background-color: #3f7d45;")
            sb.AppendLine("    }")
            sb.AppendLine("    table.archive-table th .sort-icon {")
            sb.AppendLine("      font-size: 8pt;")
            sb.AppendLine("      margin-left: 4px;")
            sb.AppendLine("      opacity: 0.8;")
            sb.AppendLine("    }")
            sb.AppendLine("    table.archive-table td {")
            sb.AppendLine("      padding: 8px 10px;")
            sb.AppendLine("      border: 1px solid #d5dec8;")
            sb.AppendLine("      vertical-align: middle;")
            sb.AppendLine("    }")
            sb.AppendLine("    table.archive-table tr:nth-child(even) td {")
            sb.AppendLine("      background-color: #fdfbf7;")
            sb.AppendLine("    }")
            sb.AppendLine("    table.archive-table tr:hover td {")
            sb.AppendLine("      background-color: #f2f7ec;")
            sb.AppendLine("    }")
            sb.AppendLine("    /* Badges */")
            sb.AppendLine("    .badge {")
            sb.AppendLine("      display: inline-block;")
            sb.AppendLine("      padding: 3px 8px;")
            sb.AppendLine("      border-radius: 12px;")
            sb.AppendLine("      font-size: 8pt;")
            sb.AppendLine("      font-weight: bold;")
            sb.AppendLine("      text-align: center;")
            sb.AppendLine("    }")
            sb.AppendLine("    .badge-approved {")
            sb.AppendLine("      background-color: #e4f4e4;")
            sb.AppendLine("      color: #1e6d24;")
            sb.AppendLine("      border: 1px solid #a3d9a7;")
            sb.AppendLine("    }")
            sb.AppendLine("    .badge-review {")
            sb.AppendLine("      background-color: #fff4db;")
            sb.AppendLine("      color: #a86c00;")
            sb.AppendLine("      border: 1px solid #fed280;")
            sb.AppendLine("    }")
            sb.AppendLine("    .badge-active {")
            sb.AppendLine("      background-color: #f0f0f0;")
            sb.AppendLine("      color: #444;")
            sb.AppendLine("      border: 1px solid #ccc;")
            sb.AppendLine("    }")
            sb.AppendLine("    /* Footer & Signatures */")
            sb.AppendLine("    .report-footer {")
            sb.AppendLine("      margin-top: 36px;")
            sb.AppendLine("      padding-top: 16px;")
            sb.AppendLine("      border-top: 1px solid #d5dec8;")
            sb.AppendLine("    }")
            sb.AppendLine("    .sig-row {")
            sb.AppendLine("      display: flex;")
            sb.AppendLine("      justify-content: space-between;")
            sb.AppendLine("      margin-bottom: 28px;")
            sb.AppendLine("    }")
            sb.AppendLine("    .sig-block {")
            sb.AppendLine("      width: 280px;")
            sb.AppendLine("      text-align: center;")
            sb.AppendLine("    }")
            sb.AppendLine("    .sig-line {")
            sb.AppendLine("      border-top: 1px solid #333;")
            sb.AppendLine("      margin-top: 48px;")
            sb.AppendLine("      padding-top: 4px;")
            sb.AppendLine("      font-weight: bold;")
            sb.AppendLine("      font-size: 10pt;")
            sb.AppendLine("    }")
            sb.AppendLine("    .sig-role {")
            sb.AppendLine("      font-size: 8.5pt;")
            sb.AppendLine("      color: #666;")
            sb.AppendLine("    }")
            sb.AppendLine("    .confidential-notice {")
            sb.AppendLine("      text-align: center;")
            sb.AppendLine("      font-size: 8pt;")
            sb.AppendLine("      color: #777;")
            sb.AppendLine("      font-style: italic;")
            sb.AppendLine("    }")
            sb.AppendLine("    /* Print media query */")
            sb.AppendLine("    @media print {")
            sb.AppendLine("      @page {")
            sb.AppendLine("        size: A4 landscape;")
            sb.AppendLine("        margin: 10mm 12mm 12mm 12mm;")
            sb.AppendLine("      }")
            sb.AppendLine("      body {")
            sb.AppendLine("        background: #ffffff !important;")
            sb.AppendLine("        padding: 0 !important;")
            sb.AppendLine("      }")
            sb.AppendLine("      .no-print {")
            sb.AppendLine("        display: none !important;")
            sb.AppendLine("      }")
            sb.AppendLine("      .report-card {")
            sb.AppendLine("        box-shadow: none !important;")
            sb.AppendLine("        border: none !important;")
            sb.AppendLine("        padding: 0 !important;")
            sb.AppendLine("        max-width: 100% !important;")
            sb.AppendLine("      }")
            sb.AppendLine("      table.archive-table th {")
            sb.AppendLine("        background-color: #346739 !important;")
            sb.AppendLine("        color: #ffffff !important;")
            sb.AppendLine("      }")
            sb.AppendLine("      table.archive-table tr:nth-child(even) td {")
            sb.AppendLine("        background-color: #f8faf5 !important;")
            sb.AppendLine("      }")
            sb.AppendLine("      tr { page-break-inside: avoid; }")
            sb.AppendLine("      thead { display: table-header-group; }")
            sb.AppendLine("    }")
            sb.AppendLine("  </style>")
            sb.AppendLine("</head>")
            sb.AppendLine("<body>")
            sb.AppendLine("  <div class=""report-card"">")

            ' Header
            sb.AppendLine("    <div class=""report-header"">")
            If Not String.IsNullOrEmpty(logoDataUrl) Then
                sb.AppendLine($"      <img src=""{logoDataUrl}"" class=""header-logo"" alt=""Barangay Logo"">")
            Else
                sb.AppendLine("      <div class=""header-logo""></div>")
            End If
            sb.AppendLine("      <div class=""header-text"">")
            sb.AppendLine("        <div class=""gov-title"">Republic of the Philippines &bull; Province of Cagayan &bull; Municipality of Piat</div>")
            sb.AppendLine("        <div class=""brgy-title"">BARANGAY STO. DOMINGO</div>")
            sb.AppendLine("        <div class=""system-title"">Document Archiving System (DASOBSDP)</div>")
            sb.AppendLine("      </div>")
            If Not String.IsNullOrEmpty(logoDataUrl) Then
                sb.AppendLine($"      <img src=""{logoDataUrl}"" class=""header-logo"" alt=""Barangay Logo"">")
            Else
                sb.AppendLine("      <div class=""header-logo""></div>")
            End If
            sb.AppendLine("    </div>")

            sb.AppendLine("    <div class=""report-title-bar"">OFFICIAL MASTER DOCUMENT ARCHIVE REPORT</div>")

            ' Summary Pills
            sb.AppendLine("    <div class=""summary-pills"">")
            sb.AppendLine($"      <div class=""pill""><div class=""pill-num"">{totalDocs}</div><div class=""pill-label"">Total Documents</div></div>")
            sb.AppendLine($"      <div class=""pill""><div class=""pill-num"" style=""color:#1e6d24;"">{approvedCount}</div><div class=""pill-label"">Approved</div></div>")
            sb.AppendLine($"      <div class=""pill""><div class=""pill-num"" style=""color:#a86c00;"">{pendingCount}</div><div class=""pill-label"">Pending Review</div></div>")
            sb.AppendLine($"      <div class=""pill""><div class=""pill-num"" style=""font-size:12pt; margin-top:6px;"">{DateTime.Now:yyyy-MM-dd HH:mm}</div><div class=""pill-label"">Generated Date</div></div>")
            sb.AppendLine($"      <div class=""pill""><div class=""pill-num"" style=""font-size:12pt; margin-top:6px;"">{SessionManager.Username}</div><div class=""pill-label"">Printed By</div></div>")
            sb.AppendLine("    </div>")

            ' Action Bar (no-print)
            sb.AppendLine("    <div class=""action-bar no-print"">")
            sb.AppendLine("      <div style=""display:flex; align-items:center; gap:8px;"">")
            sb.AppendLine("        <button class=""btn-print"" onclick=""window.print()"">&#128438; Print / Save as PDF</button>")
            sb.AppendLine("        <input type=""text"" id=""tableSearch"" class=""search-box"" placeholder=""Search rows (code, title, user)..."" onkeyup=""filterTable()"">")
            sb.AppendLine("      </div>")
            sb.AppendLine("      <div style=""display:flex; align-items:center; gap:6px;"">")
            sb.AppendLine("        <span style=""font-size:9pt; font-weight:600; color:#555;"">Filter:</span>")
            sb.AppendLine("        <button class=""filter-btn active"" onclick=""filterByStatus('all', this)"">All</button>")
            sb.AppendLine("        <button class=""filter-btn"" onclick=""filterByStatus('Approved', this)"">Approved</button>")
            sb.AppendLine("        <button class=""filter-btn"" onclick=""filterByStatus('For Review', this)"">For Review</button>")
            sb.AppendLine("      </div>")
            sb.AppendLine("    </div>")

            sb.AppendLine("    <div class=""no-print"" style=""font-size:8.5pt; color:#666; margin-bottom:12px; font-style:italic;"">")
            sb.AppendLine("      &#9432; Tip: Click any column header below to sort ascending or descending before printing.")
            sb.AppendLine("    </div>")

            ' Table
            sb.AppendLine("    <table class=""archive-table"" id=""archiveTable"">")
            sb.AppendLine("      <thead>")
            sb.AppendLine("        <tr>")
            sb.AppendLine("          <th style=""width:35px; text-align:center;"">#</th>")
            sb.AppendLine("          <th onclick=""sortTable(1)"">Document ID <span class=""sort-icon"">&#x25B4;&#x25BE;</span></th>")
            sb.AppendLine("          <th onclick=""sortTable(2)"">Document Title <span class=""sort-icon"">&#x25B4;&#x25BE;</span></th>")
            sb.AppendLine("          <th onclick=""sortTable(3)"">Document Type <span class=""sort-icon"">&#x25B4;&#x25BE;</span></th>")
            sb.AppendLine("          <th onclick=""sortTable(4)"">Uploaded By <span class=""sort-icon"">&#x25B4;&#x25BE;</span></th>")
            sb.AppendLine("          <th onclick=""sortTable(5)"">Date Uploaded <span class=""sort-icon"">&#x25B4;&#x25BE;</span></th>")
            sb.AppendLine("          <th onclick=""sortTable(6)"">Approval Status <span class=""sort-icon"">&#x25B4;&#x25BE;</span></th>")
            sb.AppendLine("          <th onclick=""sortTable(7)"">Status <span class=""sort-icon"">&#x25B4;&#x25BE;</span></th>")
            sb.AppendLine("        </tr>")
            sb.AppendLine("      </thead>")
            sb.AppendLine("      <tbody>")

            Dim rowNum As Integer = 1
            For Each row As DataRow In dt.Rows
                Dim docCode As String = row("DocumentCode").ToString()
                Dim title As String = row("Title").ToString()
                Dim docType As String = If(dt.Columns.Contains("DocumentType"), row("DocumentType").ToString(), "")
                Dim uploadedBy As String = row("UploadedBy").ToString()
                Dim dateUp As String = Convert.ToDateTime(row("DateUploaded")).ToString("yyyy-MM-dd HH:mm")
                Dim appStatus As String = row("ApprovalStatus").ToString()
                Dim status As String = row("Status").ToString()

                Dim badgeClass As String = If(appStatus = "Approved", "badge-approved", "badge-review")

                sb.AppendLine("        <tr>")
                sb.AppendLine($"          <td style=""text-align:center; color:#777; font-weight:600;"">{rowNum}</td>")
                sb.AppendLine($"          <td style=""font-weight:bold; color:#346739;"">{EscapeHtml(docCode)}</td>")
                sb.AppendLine($"          <td>{EscapeHtml(title)}</td>")
                sb.AppendLine($"          <td>{EscapeHtml(docType)}</td>")
                sb.AppendLine($"          <td>{EscapeHtml(uploadedBy)}</td>")
                sb.AppendLine($"          <td style=""white-space:nowrap;"">{dateUp}</td>")
                sb.AppendLine($"          <td><span class=""badge {badgeClass}"">{EscapeHtml(appStatus)}</span></td>")
                sb.AppendLine($"          <td><span class=""badge badge-active"">{EscapeHtml(status)}</span></td>")
                sb.AppendLine("        </tr>")
                rowNum += 1
            Next

            sb.AppendLine("      </tbody>")
            sb.AppendLine("    </table>")

            ' Footer
            sb.AppendLine("    <div class=""report-footer"">")
            sb.AppendLine("      <div class=""sig-row"">")
            sb.AppendLine("        <div class=""sig-block"">")
            sb.AppendLine("          <div class=""sig-line"">" & EscapeHtml(SessionManager.Username) & "</div>")
            sb.AppendLine("          <div class=""sig-role"">Prepared & Certified by (Administrator)</div>")
            sb.AppendLine("        </div>")
            sb.AppendLine("        <div class=""sig-block"">")
            sb.AppendLine("          <div class=""sig-line"">HON. PUNONG BARANGAY</div>")
            sb.AppendLine("          <div class=""sig-role"">Noted & Approved by</div>")
            sb.AppendLine("        </div>")
            sb.AppendLine("      </div>")
            sb.AppendLine("      <div class=""confidential-notice"">")
            sb.AppendLine("        Barangay Sto. Domingo, Piat, Cagayan &bull; Document Archiving System &bull; Official Public Record &bull; Confidential and Protected")
            sb.AppendLine("      </div>")
            sb.AppendLine("    </div>")
            sb.AppendLine("  </div>")

            ' JavaScript for sorting and filtering
            sb.AppendLine("  <script>")
            sb.AppendLine("    var currentSortCol = -1;")
            sb.AppendLine("    var sortAsc = true;")
            sb.AppendLine("")
            sb.AppendLine("    function sortTable(colIndex) {")
            sb.AppendLine("      var table = document.getElementById('archiveTable');")
            sb.AppendLine("      var tbody = table.querySelector('tbody');")
            sb.AppendLine("      var rows = Array.from(tbody.querySelectorAll('tr'));")
            sb.AppendLine("")
            sb.AppendLine("      if (currentSortCol === colIndex) {")
            sb.AppendLine("        sortAsc = !sortAsc;")
            sb.AppendLine("      } else {")
            sb.AppendLine("        currentSortCol = colIndex;")
            sb.AppendLine("        sortAsc = true;")
            sb.AppendLine("      }")
            sb.AppendLine("")
            sb.AppendLine("      rows.sort(function(rowA, rowB) {")
            sb.AppendLine("        var cellA = rowA.cells[colIndex].innerText.trim();")
            sb.AppendLine("        var cellB = rowB.cells[colIndex].innerText.trim();")
            sb.AppendLine("")
            sb.AppendLine("        // Date comparison check")
            sb.AppendLine("        var dateA = Date.parse(cellA);")
            sb.AppendLine("        var dateB = Date.parse(cellB);")
            sb.AppendLine("        if (!isNaN(dateA) && !isNaN(dateB)) {")
            sb.AppendLine("          return sortAsc ? dateA - dateB : dateB - dateA;")
            sb.AppendLine("        }")
            sb.AppendLine("")
            sb.AppendLine("        // Alphabetical comparison")
            sb.AppendLine("        var comp = cellA.localeCompare(cellB, undefined, { numeric: true, sensitivity: 'base' });")
            sb.AppendLine("        return sortAsc ? comp : -comp;")
            sb.AppendLine("      });")
            sb.AppendLine("")
            sb.AppendLine("      // Re-append rows and update row numbers")
            sb.AppendLine("      rows.forEach(function(row, idx) {")
            sb.AppendLine("        row.cells[0].innerText = idx + 1;")
            sb.AppendLine("        tbody.appendChild(row);")
            sb.AppendLine("      });")
            sb.AppendLine("    }")
            sb.AppendLine("")
            sb.AppendLine("    function filterTable() {")
            sb.AppendLine("      var query = document.getElementById('tableSearch').value.toLowerCase();")
            sb.AppendLine("      var rows = document.querySelectorAll('#archiveTable tbody tr');")
            sb.AppendLine("      var count = 0;")
            sb.AppendLine("      rows.forEach(function(row) {")
            sb.AppendLine("        var text = row.innerText.toLowerCase();")
            sb.AppendLine("        if (text.indexOf(query) > -1) {")
            sb.AppendLine("          row.style.display = '';")
            sb.AppendLine("          count++;")
            sb.AppendLine("          row.cells[0].innerText = count;")
            sb.AppendLine("        } else {")
            sb.AppendLine("          row.style.display = 'none';")
            sb.AppendLine("        }")
            sb.AppendLine("      });")
            sb.AppendLine("    }")
            sb.AppendLine("")
            sb.AppendLine("    function filterByStatus(status, btn) {")
            sb.AppendLine("      document.querySelectorAll('.filter-btn').forEach(function(b) { b.classList.remove('active'); });")
            sb.AppendLine("      btn.classList.add('active');")
            sb.AppendLine("      var rows = document.querySelectorAll('#archiveTable tbody tr');")
            sb.AppendLine("      var count = 0;")
            sb.AppendLine("      rows.forEach(function(row) {")
            sb.AppendLine("        var appStatus = row.cells[6].innerText.trim();")
            sb.AppendLine("        if (status === 'all' || appStatus.toLowerCase() === status.toLowerCase()) {")
            sb.AppendLine("          row.style.display = '';")
            sb.AppendLine("          count++;")
            sb.AppendLine("          row.cells[0].innerText = count;")
            sb.AppendLine("        } else {")
            sb.AppendLine("          row.style.display = 'none';")
            sb.AppendLine("        }")
            sb.AppendLine("      });")
            sb.AppendLine("    }")
            sb.AppendLine("  </script>")
            sb.AppendLine("</body>")
            sb.AppendLine("</html>")

            Dim tempFile As String = Path.Combine(Path.GetTempPath(), $"Barangay_Archive_Report_{DateTime.Now:yyyyMMdd_HHmmss}.html")
            File.WriteAllText(tempFile, sb.ToString(), Encoding.UTF8)

            ActivityLogger.Log(SessionManager.Username, "Success", "Admin generated and printed document archive report.")

            ' Launch in system default browser for printing
            Process.Start(New ProcessStartInfo(tempFile) With {
                .UseShellExecute = True
            })
        Catch ex As Exception
            MessageBox.Show("Error generating report: " & ex.Message, "Print Error",
                            MessageBoxButtons.OK, MessageBoxIcon.Error)
        End Try
    End Sub

    Private Function EscapeHtml(input As String) As String
        If String.IsNullOrEmpty(input) Then Return ""
        Return input.Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;").Replace("""", "&quot;")
    End Function

End Module
